# Generated by Django 2.2 on 2019-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='consumo',
            field=models.IntegerField(default=0),
        ),
    ]
