# Generated by Django 2.2 on 2019-04-19 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic  = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumo', '0002_auto_20190410_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntidadElectrica',
            new_name='Entidad',
        ),
        migrations.RenameModel(
            old_name='TarifasElectricas',
            new_name='Tarifas',
        ),
    ]
