# Generated by Django 2.2 on 2019-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_auto_20190419_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='categoria',
            field=models.CharField(default='Aires', max_length=20),
        ),
    ]
