# Generated by Django 2.2.2 on 2019-07-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0004_artefacto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='cargofijo',
            field=models.FloatField(default=0),
        ),
    ]
