# Generated by Django 2.2.4 on 2019-10-11 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumo', '0005_auto_20190726_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='zona_bioambiental',
            field=models.CharField(default='IIIb', max_length=4),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('espesor', models.FloatField(default=0)),
                ('conductividad_termica', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=10)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
