# Generated by Django 2.2.6 on 2019-11-01 01:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('consumo', '0006_auto_20191011_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='consumo.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('vivienda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consumo.Vivienda')),
                ('orientacion', models.CharField(max_length=15)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumo.Material', verbose_name='material')),
            ],
            bases=('consumo.vivienda',),
        ),
        migrations.CreateModel(
            name='Pared',
            fields=[
                ('vivienda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consumo.Vivienda')),
                ('orientacion', models.CharField(max_length=15)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumo.Material', verbose_name='material')),
            ],
            bases=('consumo.vivienda',),
        ),
    ]
