export const GET_MATERIALES = 'GET_MATERIALES';
export const GET_MATERIAL = 'GET_MATERIAL';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const EDIT_MATERIAL = 'EDIT_MATERIAL';